_wandb:
    value:
        cli_version: 0.21.1
        e:
            ejpa56ewq5eww9em3ejdsza97ah6yojk:
                args:
                    - -c
                    - /home/user01/aiotlab/sondinh/Flamingo/audio-flamingo/audio_flamingo_2/configs/vstep_lora.yaml
                codePath: audio_flamingo_2/train/train_lora.py
                codePathLocal: train_lora.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "11.4"
                disk:
                    /:
                        total: "1884194480128"
                        used: "178605027328"
                email: Son.DN225997@sis.hust.edu.vn
                executable: /home/user01/miniconda3/envs/audioflamingo2/bin/python
                git:
                    commit: 05dd8482dad5f4d871157a48d020e19637b0ee6f
                    remote: git@github.com:Etdihatthoc/Flamingo-2.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-7a55bc74-5965-06a7-64d8-d7a52d60188f
                host: dgx01
                memory:
                    total: "2164325953536"
                os: Linux-5.4.0-124-generic-x86_64-with-glibc2.31
                program: /home/user01/aiotlab/sondinh/Flamingo/audio-flamingo/audio_flamingo_2/train/train_lora.py
                python: CPython 3.10.18
                root: /home/user01/aiotlab/sondinh/Flamingo/audio-flamingo/audio_flamingo_2/train
                slurm:
                    conf: /cm/shared/apps/slurm/var/etc/slurm-hust/slurm.conf
                    cpus_on_node: "2"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_cpus_per_node: "2"
                    job_end_time: "1760202291"
                    job_gid: "1001"
                    job_id: "17342"
                    job_name: bash
                    job_nodelist: dgx01
                    job_partition: defq
                    job_start_time: "1758992691"
                    job_uid: "1001"
                    job_user: user01
                    jobid: "17342"
                    launch_node_ipaddr: 172.16.0.9
                    localid: "0"
                    mem_per_node: "1024"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dgx01
                    nprocs: "1"
                    ntasks: "1"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "34799"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "35093"
                    pty_win_col: "136"
                    pty_win_row: "32"
                    srun_comm_host: 172.16.0.9
                    srun_comm_port: "42009"
                    step_gpus: "0"
                    step_id: "1"
                    step_launcher_port: "42009"
                    step_nodelist: dgx01
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "1"
                    task_pid: "519999"
                    tasks_per_node: "1"
                    topology_addr: dgx01
                    topology_addr_pattern: node
                    umask: "0002"
                    working_cluster: slurm-hust:bcm-headnode01:6817:9984:109
                startedAt: "2025-09-28T16:57:42.065596Z"
                writerId: ejpa56ewq5eww9em3ejdsza97ah6yojk
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 63
                - 71
                - 98
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.46.3
            "8":
                - 2
            "12": 0.21.1
            "13": linux-x86_64
audio_transformer_kwargs:
    value:
        common_encoder_embed_dim: 1024
        d_inner: 2048
        max_num_media: 128
        max_window_per_audio: 1
        n_head: 8
        n_layers: 3
batch_size:
    value: 2
bias:
    value: none
cache_dir:
    value: /home/user01/.cache
cross_attn_every_n_layers:
    value: 3
dataset:
    value:
        VSTEP-SpeakingScoring/train:
            weight: 1
delete_previous_checkpoint:
    value: true
dist_backend:
    value: null
dist_url:
    value: null
expdir:
    value: ./
freeze_lm_embeddings:
    value: true
fsdp:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: true
horovod:
    value: false
lang_encoder_path:
    value: Qwen/Qwen2.5-1.5B
learning_rate:
    value: 5e-05
logging_steps:
    value: 5
lora_alpha:
    value: 16
lora_dropout:
    value: 0.1
loss_multiplier:
    value: 1
lr_scheduler:
    value: linear
max_grad_norm:
    value: 1
no_set_device_rank:
    value: true
num_epochs:
    value: 10
offline:
    value: false
precision:
    value: amp_bfloat16
r:
    value: 8
run_name:
    value: vstep-lora-1.5B
seed:
    value: 42
target_modules:
    value:
        - q_proj
        - v_proj
        - k_proj
        - o_proj
        - gate_proj
        - up_proj
        - down_proj
task_type:
    value: CAUSAL_LM
tokenizer_path:
    value: Qwen/Qwen2.5-1.5B
warmup_steps:
    value: 200
weight_decay:
    value: 0.01
