train_config:
  expdir: ./
  run_name: sft-3B
  delete_previous_checkpoint: true 
  batch_size: 8
  gradient_accumulation_steps: 2
  seed: 42
  learning_rate: 0.00002
  lr_scheduler: constant
  loss_multiplier: 1.0
  warmup_steps: 1875
  weight_decay: 0.1
  precision: amp_bf16  # ["amp_bf16", "amp_bfloat16", "bf16", "fp16", "fp32"]
  gradient_checkpointing: False 
  num_epochs: 200  # num_epochs * dataset_blending_global_weight = 1
  offline: false
  freeze_lm_embeddings: false
  logging_steps: 10
  dist_backend: nccl
  dist_url: env:// # tcp://localhost:7000
  no_set_device_rank: false 
  fsdp: true 
  fsdp_use_orig_params: false  # Passed into the FSDP constructor. Enables param_groups and gradient masking for weight_decay. Does not work with OPT.
  fsdp_sharding_strategy: full  # full, hybrid
  horovod: false

# instruction tuning hparams
sft_config:
  pretrained_path: ./sft-3B
  pretrained_ckpt: checkpoint_100.pt
  unfreeze_full_lm: false

data_config:
  dataset_blending_global_weight: 0.005

  dataset_blending_config:
    dummy/dummy:
      weight: 1.0

  dataset_file_root: DATA_MANIFEST_FOLDER
  data_root: DATA_ROOT
  dataset_blending_output: ./dummy.json
  max_tokens: 512
  num_workers: 4

  valid_dataset_config: 
    # List all test sets here
    Clotho-AQA-AQA/test: true
    Clotho-v2-AudioCaptioning/test: true
    audiocaps-AudioCaptioning/test: true

    FSD50k-EventClassification/test: true
    CochlScene-SceneClassification/test: true
    NonSpeech7k-EventClassification/test: true
    SONYC-UST-EventClassification/test: true

    MELD-EmotionClassification/test: true
    MELD-SentimentClassification/test: true
    emov-db-EmotionClassification/val: true
    jl-corpus-EmotionClassification/val: true
    tess-EmotionClassification/val: true
    IEMOCAP-EmotionClassification/val: true
    OMGEmotion-EmotionClassification/val: true
    VocalSound-VocalClassification/test: true
    
    Music-AVQA-AQA_All/test: true
    MU-LLAMA-AQA/test: true
    
    LP-MusicCaps-MSD-AudioCaptioning/test: true
    LP-MusicCaps-MC-AudioCaptioning/test: true
    LP-MusicCaps-MTT-AudioCaptioning/test: true
    MusicCaps-AudioCaptioning/test: true
    
    NSynth-MIR/test: true
    mtg-jamendo-MusicTagging/val: true
    musdbhq-InstrClassification/test: true
    # ...

clap_config:  
  method: afclap-large
  audio_embed_dim: 2048
  checkpoint: PATH_TO_AFCLAP_CHECKPOINT

  window_length: 10.0  # seconds
  window_overlap: 0.0  # seconds
  max_num_window: 12  # 2 minutes
  max_num_fewshot: 1  # number of fewshot samples (including the final one)
  finetune: true

model_config:
  cache_dir: ~/.cache

  lang_encoder_path: Qwen/Qwen2.5-3B
  tokenizer_path: Qwen/Qwen2.5-3B
  cross_attn_every_n_layers: 1
  audio_transformer_kwargs: {
    n_head: 8,
    n_layers: 3,
    d_inner: 2048,
    max_num_media: 128,  # must be >= max_num_window * num_fewshot_samples (4)
    max_window_per_audio: 1,  # must = max_num_window
    common_encoder_embed_dim: 1024
  }